---

- name: Download etcd packages
  unarchive:
    src: https://github.com/etcd-io/etcd/releases/download/v3.4.10/etcd-v3.4.10-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: create related folders for etcd
  file:
    path: "{{ item }}"
    state: directory
    mode: 700
  with_items:
    - /etc/etcd
    - /var/lib/etcd

- name: Copy certificates to destination
  copy:
    src: {{ item }}
    dest: /etc/etcd/{{ item }}
    mode: '0644'
  with_items:
    - ca.pem
    - kubernetes.pem
    - kubernetes-key.pem

- name: Distribute Configurations
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: '0644'
    backup: yes

- name: reload systemd service
  systemd:
    daemon_reload: yes
